version: '3.8'

services:
  sql-db:
    image: postgres:15.2
    container_name: pizza_order
    restart: always
    volumes:
      - ./db/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./db/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      - POSTGRES_DB=${SPRING_DATASOURCE_DB}
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5432:5432"
